# Stages of pipeline, should match with stage tag inside each job.
# Each stages executes in sequence, if previous job fails, then all the preceeding jobs are skipped.
stages:
  - mavenbuild
  - maventest
  - autodeploy
  - androidbuild
  - androidtest

# tags: "shell" should match with the tag name provided to runner, for spring runner should execute in shell.
# Notice that in petclinic project, the spring project is in root of master, if yours is in folder then cd to that folder.
maven-build:
  stage: mavenbuild
  tags:
    - shell
  script:
    - cd BackEnd
    - mvn package -B
  
# artifacts are created when job executes successfully, and can be manually downloaded from GitLab GUI.
# artifacts are not mandatory, buts it good practice, in case auto deploy fails, you can manually download the jar.
maven-test:
  stage: maventest
  tags:
    - shell
  script:
    - cd BackEnd
    - mvn test
  artifacts:
    paths:
      - BackEnd/target/*.jar
# Below stage builds, deploys and executes the jar as service.
# Make sure there is /target directory in your server, else script will fail, or use any other folder you like.
# If you are changing the folder, reflect the change in systemd-web-demo service too.
autoDeploy:
  stage: autodeploy
  tags:
   - shell
  script:
    - cd BackEnd
    - mvn package
    - sudo chmod 777 target/*.jar  
    - sudo mv target/Backend-0.0.1-SNAPSHOT.jar /src/jar/fud-project.jar
    - sudo systemctl reload fud.service 
    - sudo systemctl status fud.service
#   
#   - sudo systemctl start fud-project

    
# To build android projects
# Notice that we cd into Android_test folder which contains all Android files before building apk.    
# Ensure the tag matches with the tag created for Android runner
# Android runner should have docker as executor.
android-build:
  image: javiersantos/android-ci:latest
  stage: androidbuild
  before_script:
    - export ANDROID_SDK_ROOT=/var/lib/jenkins/android-sdk
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./FrontEnd/FUD/gradlew
    - rm ./FrontEnd/FUD/local.properties
  tags:
   - android_tag1
  script:
    - cd FrontEnd/FUD
    - ./gradlew assemble
  artifacts:
    paths:
    - FrontEnd/FUD/app/build/outputs/
    
# To run Android unit tests.   
unitTests:
  image: javiersantos/android-ci:latest
  stage: androidtest
  before_script:
    - export ANDROID_SDK_ROOT=/var/lib/jenkins/android-sdk
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - chmod +x ./FrontEnd/FUD/gradlew
  tags:
   - android_tag1
  script:
    - cd FrontEnd/FUD/
    - ./gradlew test
